### ISSUE TITLE
New terminal is opened even with one already opened

### ISSUE THREAD

**Issue by haubourg** [Ackar/markdown-command-runner#8]
Hi, thanks a lot for this great extension. 
Whatever I try, I get a new terminal instead of using the existing one.

**Comment by Ackar** [comment]
Hi @haubourg,

I unfortunately cannot reproduce the issue, and don't have much time to work on this at the moment.

However, if you'd like to make a fix, pull requests are very welcome! 🙂

**Comment by haubourg** [comment]
No worries, that was a feedback. I'm already too much involved in other open source projects. Let's close if you can't reproduce. I'll reopen if this occurs again (I haven't been coding for a while)

**Comment by lnicot01** [comment]
Hello, to temporarily solve this problem, you can comment this test (in `extension.ts`):
```
// a + in the state indicates a process running in foreground
if (!stdout.includes('+')) {
	term = vscode.window.createTerminal();
}
```

**Comment by aowji** [comment]
I encountered the same issue. When using this plugin in the WSL Ubuntu environment, it always opens a new terminal every time. I also debug the code, stdout always be 'S\n'
```js
// a + in the state indicates a process running in foreground
if (!stdout.includes('+')) {
        term = vscode.window.createTerminal();
}
```
